[[libsqm]]
arch = "aarch64"
git-tree-sha1 = "78f230ad2f74c9ff890913622f39c599c8ed7a34"
libgfortran_version = "5.0.0"
os = "macos"

    [[libsqm.download]]
    sha256 = "7c122ed732bac6743896eadea66ec7c4aa1008f5c84848f4dacafc4750d8f05c"
    url = "https://github.com/panxl/libsqm_jll.jl/releases/download/libsqm-v21.0.0+0/libsqm.v21.0.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[libsqm]]
arch = "aarch64"
git-tree-sha1 = "0e2795248e17d0540bd0e84c210b7c7dc4afb846"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[libsqm.download]]
    sha256 = "94b724d80ddeaa8752b5b56a57dd4196703465f5402811a1238b649802643cce"
    url = "https://github.com/panxl/libsqm_jll.jl/releases/download/libsqm-v21.0.0+0/libsqm.v21.0.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[libsqm]]
arch = "aarch64"
git-tree-sha1 = "396e85af08d3bd41ce19e8a61e78a3156dd0858d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[libsqm.download]]
    sha256 = "4dcde18afc91615620b0642e7f45d5e08d15fc4ded366c8fe3ca74a1fc942506"
    url = "https://github.com/panxl/libsqm_jll.jl/releases/download/libsqm-v21.0.0+0/libsqm.v21.0.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[libsqm]]
arch = "aarch64"
git-tree-sha1 = "e3a41d24f914629f365527d67752976515a27cdf"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[libsqm.download]]
    sha256 = "dc22be4a592e250bdd676ec9d7f45432e9541ed01fcc452cca7fcf3b3fb20fd4"
    url = "https://github.com/panxl/libsqm_jll.jl/releases/download/libsqm-v21.0.0+0/libsqm.v21.0.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[libsqm]]
arch = "x86_64"
git-tree-sha1 = "e64bbbd97ca893883019c8b0a146f3f6392177ea"
libgfortran_version = "3.0.0"
os = "macos"

    [[libsqm.download]]
    sha256 = "55181886a9929bb16931062e5e46ca4b76e22793a79afa8d67a9d26f4325f84a"
    url = "https://github.com/panxl/libsqm_jll.jl/releases/download/libsqm-v21.0.0+0/libsqm.v21.0.0.x86_64-apple-darwin-libgfortran3.tar.gz"
[[libsqm]]
arch = "x86_64"
git-tree-sha1 = "b790c164b781fdf53723bc91ac5667745f741c90"
libgfortran_version = "4.0.0"
os = "macos"

    [[libsqm.download]]
    sha256 = "f75237760ad931029a1ce44c99321eba544f06a81e37c3117599295984f1ca0b"
    url = "https://github.com/panxl/libsqm_jll.jl/releases/download/libsqm-v21.0.0+0/libsqm.v21.0.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[libsqm]]
arch = "x86_64"
git-tree-sha1 = "8e375b81a6708d7b554c180cde95ff815dc7172a"
libgfortran_version = "5.0.0"
os = "macos"

    [[libsqm.download]]
    sha256 = "3d21eb8eff936f09bb570112176927cd21a877d43187a83d9e8660dfb3164fe8"
    url = "https://github.com/panxl/libsqm_jll.jl/releases/download/libsqm-v21.0.0+0/libsqm.v21.0.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[libsqm]]
arch = "x86_64"
git-tree-sha1 = "238fffe1951ff1d791f8fa1fd5df4d3ed8edcbfb"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[libsqm.download]]
    sha256 = "891d90540f30f89c9aec67a560362de9f09833fafc9c2c97c8a8b745d83b29a0"
    url = "https://github.com/panxl/libsqm_jll.jl/releases/download/libsqm-v21.0.0+0/libsqm.v21.0.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[libsqm]]
arch = "x86_64"
git-tree-sha1 = "7795c3818389d29481e0e9c62bd06805f8ab142c"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[libsqm.download]]
    sha256 = "19197263935179b78e104518930768a050507d8fd6cefc16fe47bc65903baa30"
    url = "https://github.com/panxl/libsqm_jll.jl/releases/download/libsqm-v21.0.0+0/libsqm.v21.0.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[libsqm]]
arch = "x86_64"
git-tree-sha1 = "8a0c34ffba4992f0dd018fe92e252d3a6f438ade"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[libsqm.download]]
    sha256 = "6eb1b779bd2f06e0098d5912024d0d44b9c6dc176f0688a18da55d756a9af628"
    url = "https://github.com/panxl/libsqm_jll.jl/releases/download/libsqm-v21.0.0+0/libsqm.v21.0.0.x86_64-linux-gnu-libgfortran5.tar.gz"
