[[libsqm]]
arch = "aarch64"
git-tree-sha1 = "31344e700d2144155407f749a1f67710df634aad"
libgfortran_version = "5.0.0"
os = "macos"

    [[libsqm.download]]
    sha256 = "1ef3d4e3189e2296841b8cbca6d284cfb05dfdc6ae249209406b4bca25044f5e"
    url = "https://github.com/panxl/libsqm_jll.jl/releases/download/libsqm-v21.0.0+0/libsqm.v21.0.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[libsqm]]
arch = "aarch64"
git-tree-sha1 = "cca142799b4590f358025950c507605da92d8429"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[libsqm.download]]
    sha256 = "3f2ad1bbc9a1c957d21556a2162e95c64a52a7d14654af7e8e530c4546605b0f"
    url = "https://github.com/panxl/libsqm_jll.jl/releases/download/libsqm-v21.0.0+0/libsqm.v21.0.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[libsqm]]
arch = "aarch64"
git-tree-sha1 = "28fd800d5f57956470c29ef1036591ec92b60c2a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[libsqm.download]]
    sha256 = "0dc0f6b27f4302e284ca8ea856493fc47be00c742b0ea6478f776cbd4e78cae6"
    url = "https://github.com/panxl/libsqm_jll.jl/releases/download/libsqm-v21.0.0+0/libsqm.v21.0.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[libsqm]]
arch = "aarch64"
git-tree-sha1 = "3a2975fa108249cef4f4ae83e0e3a34648ed3f1f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[libsqm.download]]
    sha256 = "0215fbc5d44c520b965265881fcc1bdb357effaae85cddcaf732d810e1a1ea60"
    url = "https://github.com/panxl/libsqm_jll.jl/releases/download/libsqm-v21.0.0+0/libsqm.v21.0.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[libsqm]]
arch = "x86_64"
git-tree-sha1 = "9447e07f99d0a7ada6d4ed86ccf3e44cbc7e35ba"
libgfortran_version = "3.0.0"
os = "macos"

    [[libsqm.download]]
    sha256 = "eb30b339ef81088879d4a2784d45b52fb6aaf285a75195cc4840179b75920eb2"
    url = "https://github.com/panxl/libsqm_jll.jl/releases/download/libsqm-v21.0.0+0/libsqm.v21.0.0.x86_64-apple-darwin-libgfortran3.tar.gz"
[[libsqm]]
arch = "x86_64"
git-tree-sha1 = "59d02f99ae170b7d11d6819bc1b2a052be210b69"
libgfortran_version = "4.0.0"
os = "macos"

    [[libsqm.download]]
    sha256 = "68fde4a6c423ad73c0f425b080c8b82865d2886911a41f0b0c7bf6e8ab711d6f"
    url = "https://github.com/panxl/libsqm_jll.jl/releases/download/libsqm-v21.0.0+0/libsqm.v21.0.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[libsqm]]
arch = "x86_64"
git-tree-sha1 = "e0c75e7d479c8ae39e28a32d53fe9e5c09378ff2"
libgfortran_version = "5.0.0"
os = "macos"

    [[libsqm.download]]
    sha256 = "66804a70e30e31ed6c24936ef526c08b5d2095efc942b771d0ab3a1fe3481ded"
    url = "https://github.com/panxl/libsqm_jll.jl/releases/download/libsqm-v21.0.0+0/libsqm.v21.0.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[libsqm]]
arch = "x86_64"
git-tree-sha1 = "1e3c0555a89bb16484cffe841e8082cdb6fba78f"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[libsqm.download]]
    sha256 = "10b4fca005c7c3ee00a1d4793453c828a50ba4ddc8a711400ee9a8c0e9ed09fc"
    url = "https://github.com/panxl/libsqm_jll.jl/releases/download/libsqm-v21.0.0+0/libsqm.v21.0.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[libsqm]]
arch = "x86_64"
git-tree-sha1 = "45228a09c005c1cc1dbb533267e38d48eaf6949e"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[libsqm.download]]
    sha256 = "1d176dbac0d257a4af63a930953db4b45504e6da4de6e738eae5cb310b8b0802"
    url = "https://github.com/panxl/libsqm_jll.jl/releases/download/libsqm-v21.0.0+0/libsqm.v21.0.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[libsqm]]
arch = "x86_64"
git-tree-sha1 = "6054e24e21f294964f847d673215dc8784478dfe"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[libsqm.download]]
    sha256 = "4f67693d2f582985acf6a8dc3d53265194d09bd70418d009228d1dad22e8becb"
    url = "https://github.com/panxl/libsqm_jll.jl/releases/download/libsqm-v21.0.0+0/libsqm.v21.0.0.x86_64-linux-gnu-libgfortran5.tar.gz"
