# Autogenerated wrapper script for libsqm_jll for aarch64-apple-darwin-libgfortran5
export libsqm

using CompilerSupportLibraries_jll
using OpenBLAS32_jll
JLLWrappers.@generate_wrapper_header("libsqm")
JLLWrappers.@declare_library_product(libsqm, "@rpath/libsqm.dylib")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, OpenBLAS32_jll)
    JLLWrappers.@init_library_product(
        libsqm,
        "lib/libsqm.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
